### ISSUE TITLE
Project has no LICENSE

### ISSUE THREAD

**Issue by aschrijver** [msummers/activityPub4j#1]
I am creating a new _developer resources_ page for the Feneas wiki research area and noticed that your project has no LICENSE, which technically makes it proprietary and not open-source.

On the [~~ActivityPub watchlist~~](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) (moved to: [Codeberg](https://codeberg.org/fediverse/delightful-activitypub-development/)) you were in the "It's dead, Jim" category, but on the new page there is no expiry for developer code, unless there is no clarity on the actual license you adhere to (we only list open source projects).

**Comment by FireMasterK** [comment]
See https://choosealicense.com/no-permission/ for more details.

**Comment by unbeatable-101** [comment]
I emailed the maintainer and they said they would add the Apache 2.0 licence tomorrow

**Comment by aschrijver** [comment]
Thank you! I updated the watchlist to reflect that.

**Comment by Quix0r** [comment]
https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps <-- Dead link!

**Comment by aschrijver** [comment]
Yes indeed. The Feneas organization has shut down and the watchlists have moved to new locations on https://Codeberg.org/fediverse and also you can find them by navigating to https://delightful.club

Thanks for the heads-up! I'll edit the top-level text...

**Comment by Quix0r** [comment]
You are welcome. Better lock this topic because everything important is said.
